### ISSUE TITLE
Stack trace

### ISSUE THREAD

**Issue by zokrezyl** [mlang/ass#1]
Hi, 

was intending to build something similar, but given your advanced work, wanted to try it out. Unfortunately no luck:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/mihaly.elekes/work/github/mlang/ass/ass/__init__.py", line 26, in <module>
    import ass.tools.tts
  File "/Users/mihaly.elekes/work/github/mlang/ass/ass/tools/tts.py", line 21, in <module>
    class SoundIcon(BaseModel):
/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 205, in __new__
    complete_model_class(
/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 534, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/main.py", line 643, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 512, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 784, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 591, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 947, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1134, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1890, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1871, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 789, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 835, in match_type
    return self._literal_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1250, in _literal_schema
    assert expected, f'literal "expected" cannot be empty, obj={literal_type}'
           ^^^^^^^^
AssertionError: literal "expected" cannot be empty, obj=typing.Literal[()]

```

**Comment by mlang** [comment]
Looks like Python 3.12+Pydantic doesn't like Literal[*foo].

As a temporary remedy, you can uncomment the line

import ass.tools.tts

in ass/__init__.py

-- 
CYa,
  ⡍⠁⠗⠊⠕
